services:
  db:
    image: postgres:18-alpine
    container_name: sarir_db
    environment:
      POSTGRES_USER: sarir_user
      POSTGRES_PASSWORD: "Sarir@2026"
      POSTGRES_DB: sarir
    volumes:
      - db18_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sarir_user -d sarir"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db18_data:
